### ISSUE TITLE
"About" panel visible on bottom of screen on large viewports.

### ISSUE THREAD

**Issue by berbaquero** [cheeaun/hackerweb#37]
![screen shot 2014-11-06 at 11 00 15](https://cloud.githubusercontent.com/assets/1769951/4934110/4b0ab4fc-659e-11e4-92f0-fcde553fc48d.png)

Granted, I'm overriding the UA string to get and use the iOS theme on desktop rather than the "web" theme (where this doesn't happen, of course).

Maybe it's not worth looking too much into this one, but just wanted to let you know. :)

**Comment by cheeaun** [comment]
Wow, 2014 :scream: Anyway better late than never :stuck_out_tongue: Fixed in d38903e57589f0f0e1a76f34ba258eb6f4fdd67c
