### ISSUE TITLE
No comments on iOS Safari sometimes

### ISSUE THREAD

**Issue by christiangenco** [cheeaun/hackerweb#51]
About 40% of the time when I load hackerweb in Safari, the comments don't load:

![img_1755](https://cloud.githubusercontent.com/assets/179361/12656456/f62a7eae-c5c3-11e5-8827-1e7571d3f698.PNG)

or show as "Loading...":

![img_1753](https://cloud.githubusercontent.com/assets/179361/12656455/f615b1b8-c5c3-11e5-9a70-62abbf79c67f.PNG)

Though they're definitely there:

![img_1754](https://cloud.githubusercontent.com/assets/179361/12656446/f1bc7f8e-c5c3-11e5-8d83-d549b5bf5285.PNG)

**Comment by cheeaun** [comment]
This was mainly related to the API backend. Should be fixed by now.

If you're facing this problem again, feel free to create another issue.
