### ISSUE TITLE
Dark mode feature request

### ISSUE THREAD

**Issue by pahakalle** [cheeaun/hackerweb#57]
A dark mode would be nice for when reading at night 😄

**Comment by cheeaun** [comment]
Turns out that someone else made a user style for dark mode here https://github.com/tzekid/stylish_styles#hackernewswebapp---dark

**Comment by popey456963** [comment]
An alternative to stylish, which IIRC has had complaints of malware recently is DarkReader[0][1].  Examples:

![](https://femto.pw/p2hm.png)

![](https://femto.pw/8g6y.png)

[0] https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en
[1] https://addons.mozilla.org/en-US/firefox/addon/darkreader/
