### ISSUE TITLE
remove cloudflare

### ISSUE THREAD

**Issue by glaszig** [cheeaun/hackerweb#58]
using cloudflare is hostile to users using tor, valueing privacy and cloudflare is doing shit to improve the situation.

![img_4467](https://cloud.githubusercontent.com/assets/201135/22080290/569bb2bc-ddbf-11e6-94f4-0e2764ee4b00.PNG)

please use another method or service which works properly. dump cloudflare.

**Comment by glaszig** [comment]
also, [cloudbleed](https://bugs.chromium.org/p/project-zero/issues/detail?id=1139).

**Comment by pahakalle** [comment]
This might help, you could allow all tor users trough or use the JavaScript Challenge https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-
